server:
    port: 7072

spring:
    application:
        name: mall-gateway


    cloud:
      gateway:
        routes:
          - id: test
            uri: test.do
            predicates:
                - Method=GET,POST

