server:
  port: 7076

  # tomcat服务器配置
  tomcat:
    threads:
      max: 256
      min-spare: 8
    uri-encoding: UTF-8

alibaba:
  cloud:
    access-key: LTAI5t5i2CF3vnosEsZvNq83
    secret-key: Jz90M0TyxHpx4rgnuoKiEDZuoG4dmy
    oss:
      endpoint: oss-cn-chengdu.aliyuncs.com

spring:
  application:
    name: mall-product

  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_pms?useUnicode=true&characterEncoding=utf8
      &useSSL=false&serverTimeZone=GMT+8

    hikari:
      minimum-idle: 4
      maximum-pool-size: 16

  # spring 线程池配置
  task:
    execution:
      pool:
        core-size: 8
        max-size: 32

  # cloud 配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # jackson 序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus 配置
mybatis-plus:
  # 默认路径 ant风格路径通配符
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    banner: false
    db-config:
      id-type: auto

# 日志配置
logging:
  level:
    com.yangzl.mall.product.dao: debug
