server:
  port: 7074

  # tomcat服务器配置
  tomcat:
    threads:
      max: 128
      min-spare: 8
    uri-encoding: UTF-8


spring:
  application:
    name: mall-order

  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_pms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8

    hikari:
      minimum-idle: 2
      maximum-pool-size: 16

  # spring 线程池配置
  task:
    execution:
      pool:
        core-size: 8
        max-size: 32

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    banner: false
    db-config:
      id-type: auto
